#ifndef CONFIG_H
#define CONFIG_H

#define KERNEL_CODE_SELECTOR          0x08
#define KERNEL_DATA_SELECTOR          0x10

#define PEACH_OS_TOTAL_INTERRUPTS     512

#define PEACH_OS_HEAP_SIZE_BYTES      104857600   // 100MB
#define PEACH_OS_BLOCK_SIZE_BYTES     4096
#define PEACH_OS_HEAP_ADDRESS         0x01000000
#define PEACH_OS_HEAP_TABLE_ADDRESS   0x00007e00

#define PEACH_OS_SECTOR_SIZE          512

#define PEACH_OS_MAX_FILE_SYSTEMS         12
#define PEACH_OS_MAX_FILE_DESCRIPTORS     12


#endif